version: '3.1'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: vue-starter
        restart: always
        tty: true
        environment:
            SERVICE_NAME: vue-starter
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: vue-starter-webserver
        restart: always
        tty: true
        ports:
            - "8000:80"
            #  - "4431:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel

    #MySQL Service
    db:
        image: mysql:8.0.17
        container_name: vue-starter-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: 123456
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
    npm:
        image: node:13.7
        container_name: npm
        volumes:
            - ./:/var/www
        ports:
            - 3000:3000
            - 3001:3001
        working_dir: /var/www
        entrypoint: ['npm']
        networks:
            - laravel

#Docker Networks
networks:
    laravel:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local

